theme: jekyll-theme-merlot
title : "Welcome to the Angular6 i18n demo Page"
description : "This repo is part of a tutorial where we explain how internationalize an Angular 6 application, also know as i18n. Internationalizing our app means that it will be available in different languages, we will have a multi language angular website. The good news is that the new Angular CLI can help us with this task."
